### ISSUE TITLE
NullPointerException when trying to create a calendar on Android

### ISSUE THREAD

**Issue by eliseyOzerov** [builttoroam/device_calendar#216]
Here's my code: `final Result<String> newCalendarID = await plugin.createCalendar("Activities", calendarColor: Color(0xff1D275B));`

Here's the stacktrace: `MethodChannel#plugins.builttoroam.com/device_calendar(30084): Failed to handle method call
E/MethodChannel#plugins.builttoroam.com/device_calendar(30084): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/MethodChannel#plugins.builttoroam.com/device_calendar(30084): 	at android.os.Parcel.createException(Parcel.java:2094)
E/MethodChannel#plugins.builttoroam.com/device_calendar(30084): 	at android.os.Parcel.readException(Parcel.java:2056)
E/MethodChannel#plugins.builttoroam.com/device_calendar(30084): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
E/MethodChannel#plugins.builttoroam.com/device_calendar(30084): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
E/MethodChannel#plugins.builttoroam.com/device_calendar(30084): 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:481)
E/MethodChannel#plugins.builttoroam.com/device_calendar(30084): 	at android.content.ContentResolver.insert(ContentResolver.java:1835)
E/MethodChannel#plugins.builttoroam.com/device_calendar(30084): 	at com.builttoroam.devicecalendar.CalendarDelegate.createCalendar(CalendarDelegate.kt:254)`

Any ideas?

**Comment by Brett09** [comment]
Which device did you use to get the exception? I've tried on an Android emulator (Nexus 5 API 29) and cannot reproduce this issue.

**Comment by eliseyOzerov** [comment]
I'm running it on an emulator with API 29 as well.

**Comment by eliseyOzerov** [comment]
any updates on this?

**Comment by eliseyOzerov** [comment]
@Brett09 i've got a feature on hold bcs of this. Please check out what's going on with this issue. As I've said, on the emulator it works fine, but throws an exception on the device. I'm using Samsung Galaxy S9+ for testing. It has something to do with the ContentResolver on line 254 in CalendarDelegate.kt, but I wasn't able to debug it as it was telling me in the ContentResolver file that bytecode doesn't match source code (but that's a different topic I guess).

**Comment by Alimoes** [comment]
Following! It does work when I disable/logout iCloud or Gmail account on the device. But normally I have the exact same error on both IOS and Android as most have either iCloud or gmail enabled.

**Comment by mmc16** [comment]
I'm having the same issue...
Has anyone found another workaround? Because I can't disable Gmail....

**Comment by petekblaz** [comment]
Any info on this? A workaround perhaps?

**Comment by Pranjal2041** [comment]
The problem is with CalendarContract.Calendars.CALENDAR_COLOR on line 251. Due to some reasons it is unable to parse the hexadecimal color code. A workaround is to conert the color to int value using Color.parse function of android.graphics.colors library. #232

**Comment by nickrandolph** [comment]
@eliseyOzerov / @Alimoes / @mmc16 / @petekblaz / @Pranjal2041 can you run the example app (from develop branch) and verify the fix that @Pranjal2041 has made (now merged) fixes this issue

**Comment by mmc16** [comment]
@nickrandolph, I did that and it worked for me

**Comment by PingAK9** [comment]
+1, Same

**Comment by andzejsw** [comment]
Please everyone, who have experienced this issue take a look un latest 4.x development version and see if issue is fixed

**Comment by gnunicorn** [comment]
still seeing this on `4.3.3-20240801`, in particular for Moto G8 with Android 11...

**Comment by gnunicorn** [comment]
After some investigating and using lambdatests to run this in various configurations, I can confirm that it was broken on a "Samsung S9+" (Android 10) as well as a "One Plus Nord" (Android 11) for the released version, but both work well using latest `develop`-branch.
