### ISSUE TITLE
A serious error occurred on the android phone, causing the system calendar to crash

### ISSUE THREAD

**Issue by taoweiji** [builttoroam/device_calendar#218]
2020-04-10 01:30:05.190 32256-32297/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.oneplus.calendar, PID: 32256
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.NumberFormatException: For input string: "0xfff44336"
        at java.lang.Integer.parseInt(Integer.java:615)
        at java.lang.Integer.parseInt(Integer.java:650)
        at android.database.MatrixCursor.getInt(MatrixCursor.java:284)
        at com.android.calendar.EventInfoFragment$AgendaQueryAsyncTask.doInBackground(EventInfoFragment.java:737)
        at com.android.calendar.EventInfoFragment$AgendaQueryAsyncTask.doInBackground(EventInfoFragment.java:688)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by mmc16** [comment]
pre-production reported the same issue
![Screenshot_2020-06-05-08-01-59-224_com miui bugreport](https://user-images.githubusercontent.com/27312683/83876278-fb8e2900-a70e-11ea-9be3-df896e2c9a38.jpg)

![Screenshot_2020-06-05-08-05-57-939_com android settings](https://user-images.githubusercontent.com/27312683/83876225-e6b19580-a70e-11ea-856b-454afb654db5.jpg)

**Comment by nickrandolph** [comment]
@taoweiji / @mmc16 do you see this issue if you run the example app that's part of the device calendar source code? If so, would you be able to provide more context on where the error is occurring.

**Comment by andzejsw** [comment]
Closing, since there is no news about this issue for more than one year.
