### ISSUE TITLE
SQLiteException on checking if event exists

### ISSUE THREAD

**Issue by fardeen9983** [builttoroam/device_calendar#248]
## Task
Check if an Event exists by ID

### Code :
```dart
Future<bool> checkCalendarEvent(String id, String email) async {
    try {
      List<Calendar> calendars = await _retrieveCalendars();
      if (calendars != null) {
        var temp = calendars
            .where((element) =>
                element.isDefault &&
                !element.isReadOnly &&
                element.name.contains(email))
            .toList();
        calendars = temp.length != 0
            ? temp
            : calendars.where((element) => element.isDefault).toList();
        Calendar calendar = calendars[0];

        Result<UnmodifiableListView<Event>> result = await _deviceCalendarPlugin
            .retrieveEvents(calendar.id, RetrieveEventsParams(eventIds: [id]));
        return result.isSuccess && result.data.length > 0 ? true : false;
      }
      return false;
    } on Exception catch (e) {
      print("$e");
      return false;
    }
  }
```
### Exception generated :
```
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): Failed to handle method call
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): android.database.sqlite.SQLiteException: no such column: HLhOw1lfEvi4hZ0joKz5 (code 1 SQLITE_ERROR): , while compiling: SELECT Instances.event_id AS event_id, title, description, begin, end, duration, rdate, rrule, allDay, eventLocation, customAppUri FROM Instances INNER JOIN view_events AS Events ON (Instances.event_id=Events._id) WHERE (begin<=? AND end>=?) AND ((calendar_id = 4) AND (deleted != 1) AND ((event_id = HLhOw1lfEvi4hZ0joKz5))) ORDER BY dtstart ASC
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:437)
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): 	at android.content.ContentResolver.query(ContentResolver.java:962)
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): 	at android.content.ContentResolver.query(ContentResolver.java:890)
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): 	at android.content.ContentResolver.query(ContentResolver.java:846)
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): 	at com.builttoroam.devicecalendar.CalendarDelegate.retrieveEvents(CalendarDelegate.kt:291)
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): 	at com.builttoroam.devicecalendar.DeviceCalendarPlugin.onMethodCall(DeviceCalendarPlugin.kt:103)
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): 	at android.app.ActivityThread.main(ActivityThread.java:7710)
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/MethodChannel#plugins.builttoroam.com/device_calendar(16108): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/flutter (16108): PlatformException(error, no such column: HLhOw1lfEvi4hZ0joKz5 (code 1 SQLITE_ERROR): , while compiling: SELECT Instances.event_id AS event_id, title, description, begin, end, duration, rdate, rrule, allDay, eventLocation, customAppUri FROM Instances INNER JOIN view_events AS Events ON (Instances.event_id=Events._id) WHERE (begin<=? AND end>=?) AND ((calendar_id = 4) AND (deleted != 1) AND ((event_id = HLhOw1lfEvi4hZ0joKz5))) ORDER BY dtstart ASC, null)
```

**Comment by nickrandolph** [comment]
Which version of the plugin is this - please check lock file for actual version.

**Comment by nickrandolph** [comment]
Also, where did the event id that you're trying to retrieve come from?

**Comment by fardeen9983** [comment]
I tried setting the event Id to a previously acquired key from firestore. I wanted to have the resulting event which i was adding to the calendar have this id only so i could fetch it with this reference. 

In the end i realised from the result of createOrUpdateEvent contains a unique key the package automatically creates, discarding my own key.

How can I achieve this .i.e, my custom id for event i am storing?

**Comment by fardeen9983** [comment]
Here is the code i use to save the event
```
Future<bool> addToCalendar(context, BookingModel model, {bool isBusiness = false}) async { String email = Provider.of<CurrentUserProvider>(context, listen: false).user.email; try { List<Calendar> calendars = await _retrieveCalendars(); if (calendars != null) { var temp = calendars .where((element) => element.isDefault && !element.isReadOnly && element.name.contains(email)) .toList(); calendars = temp.length != 0 ? temp : calendars.where((element) => element.isDefault).toList(); Calendar calendar = calendars[0]; print(calendar.name); String services = model.services.fold( '', (previousValue, element) => previousValue + ", " + element['title']); services = services.substring(2, services.length); String staff = "Anyone"; if (!model.withAnyone) { staff = model.staff .map((e) => e['name']) .toList() .fold( "", (previousValue, element) => previousValue + ", " + element.toString().toUpperCase()) .toString(); staff = staff.substring(2, staff.length); } else staff = "Anyone"; String time = DateFormat("dd MMMM yy, h:mm a") .format(DateTime.fromMicrosecondsSinceEpoch(model.appointedDate)); DateTime dateTime = DateTime.fromMicrosecondsSinceEpoch(model.appointedDate); dateTime = DateTime(dateTime.year, dateTime.month, dateTime.day, 23, 59); if (model.status == BookingStatus.CONFIRMED) { Event event = Event( calendar.id, eventId: model.id, allDay: false, end: dateTime, title: isBusiness ? "Booking by ${model.uName}" : "Booking at ${model.bName}", description: "${isBusiness ? "You have an upcoming booking on $time" : "Your booking has been confirmed on $time"}." "\n\nFollowing services are requested:\n$services" "\n\nRequested Staff Members:\n$staff", start: DateTime.fromMicrosecondsSinceEpoch(model.appointedDate), ); Result<String> result = await _deviceCalendarPlugin.createOrUpdateEvent(event); if (result.isSuccess) { SharedPreferences prefs = await SharedPreferences.getInstance(); prefs.setString(model.id, result.data); } return result.isSuccess; } else return false; } return false; } on Exception catch (e) { print("$e"); return false; } }
```
As you can see I passing the model id for event Id. I want this to be the resulting event id as well

**Comment by nickrandolph** [comment]
I think you have to use the url property

**Comment by nickrandolph** [comment]
@fardeen9983 are you ok with me closing this issue?
