### ISSUE TITLE
Error: NoSuchMethodError: The getter 'key' was called on null. Receiver: null Tried calling: key

### ISSUE THREAD

**Issue by javadkt** [builttoroam/device_calendar#261]
Getting error in iPhone 11 Pro Max and Nokia  TA-1004 with release build when creating the calendar. I am calling below method to create a calendar but throwing error. But the same App build works in many other android devices and working fine in iPhone 11 Pro Max simulator but not working in iPhone 11 Pro Max physical device.

```
_deviceCalendarPlugin.createCalendar(
          Strings.calendarName,
          localAccountName: Strings.calendarName,
        )
```

Stack trace:
#0 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3470)
#1 MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991)
#2 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490)
#3 Element.updateChild (package:flutter/src/widgets/framework.dart:3258)
#4 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571)
#5 Element.rebuild (package:flutter/src/widgets/framework.dart:4262)
#6 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525)
#7 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520)
#8 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490)
#9 MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991)
#10 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490)
#11 Element.updateChild (package:flutter/src/widgets/framework.dart:3258)
#12 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874)
#13 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490)
#14 Element.updateChild (package:flutter/src/widgets/framework.dart:3258)
#15 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874)
#16 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490)
#17 Element.updateChild (package:flutter/src/widgets/framework.dart:3258)
#18 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571)
#19 Element.rebuild (package:flutter/src/widgets/framework.dart:4262)
#20 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525)
#21 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520)
#22 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490)
#23 Element.updateChild (package:flutter/src/widgets/framework.dart:3258)
#24 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571)
#25 Element.rebuild (package:flutter/src/widgets/framework.dart:4262)
#26 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525)
#27 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520)
#28 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490)
#29 Element.updateChild (package:flutter/src/widgets/framework.dart:3258)
#30 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571)
#31 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719)
#32 Element.rebuild (package:flutter/src/widgets/framework.dart:4262)
#33 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525)
#34 StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710)
#35 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520)
#36 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490)
#37 Element.updateChild (package:flutter/src/widgets/framework.dart:3258)
#38 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571)
#39 Element.rebuild (package:flutter/src/widgets/framework.dart:4262)
#40 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525)
#41 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520)
#42 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490)
#43 Element.updateChild (package:flutter/src/widgets/framework.dart:3258)
#44 SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1164)
#45 SliverMultiBoxAdaptorElement.createChild. (package:flutter/src/widgets/sliver.dart:1149)
#46 BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620)
#47 SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1142)
#48 RenderSliverMultiBoxAdaptor._createOrObtainChild. (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:356)
#49 RenderObject.invokeLayoutCallback. (package:flutter/src/rendering/object.dart:1868)
#50 BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2558)
#51 RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1868)
#52 RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:345)
#53 RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:491)
#54 RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:233)
#55 RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:276)
#56 RenderObject.layout (package:flutter/src/rendering/object.dart:1769)
#57 RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137)
#58 RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:377)
#59 RenderObject.layout (package:flutter/src/rendering/object.dart:1769)
#60 RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:471)
#61 RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1465)
#62 RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1374)
#63 RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632)
#64 PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889)
#65 RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404)
#66 WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867)
#67 RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286)
#68 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117)
#69 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056)
#70 SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972)
#71 _rootRun (dart:async/zone.dart:1190)
#72 _CustomZone.run (dart:async/zone.dart:1093)
#73 _CustomZone.runGuarded (dart:async/zone.dart:997)
#74 _invoke (dart:ui/hooks.dart:253)
#75 _drawFrame (dart:ui/hooks.dart:211)

**Comment by andzejsw** [comment]
Is this issue still a problem with latest dev?

**Comment by javadkt** [comment]
> Is this issue still a problem with latest dev?

not checked with the latest one

**Comment by andzejsw** [comment]
Error message doesn't help at all. It shows only widget drawing tree error, but nothin related to plugin. Van it be, that calendars are read correctly, but just there is issue in your app just with calendars visual representation!?
